[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
remappings = [
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/local/=lib/chainlink-local/',
     '@chainlink/contracts-ccip/=lib/ccip/contracts/',
       '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/'
]


[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
